---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo
spec:
  containers:
  - name: demo-container
    image: 039096978268.dkr.ecr.us-east-1.amazonaws.com/webapp
    command: ['sh', '-c', 'echo Hello World! && sleep 300']
